entails: insert('⊨')
implies: insert('⇒')
biconditional: insert('⇔')
equivalent: insert('≡')
negate: insert('¬')
for all: insert('∀')
exists: insert('∃')

subset: insert('⊆')
strict subset: insert('⊂')